{
 "title": "ingest-v3",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"ingest-v3.*\", cpu=\"total\", container=\"ingest-v3\"}[1m])",
     "legendFormat": "{{pod}}-usage"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{pod=~\"ingest-v3.*\"}",
     "legendFormat": "{{pod}}-requests"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{pod=~\"ingest-v3.*\"}",
     "legendFormat": "{{pod}}-limits"
    }
   ]
  },
  {
   "title": "MEM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~\"ingest-v3.*\", container=\"ingest-v3\"}",
     "legendFormat": "{{pod}}-usage"
    },
    {
     "expr": "container_spec_memory_limit_bytes{pod=~\"ingest-v3.*\", container=\"ingest-v3\"}",
     "legendFormat": "{{pod}}-limits"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{pod=~\"ingest-v3.*\"}[1m])",
     "legendFormat": "{{pod}}-receive"
    },
    {
     "expr": "-rate(container_network_transmit_bytes_total{pod=~\"ingest-v3.*\"}[1m])",
     "legendFormat": "{{pod}}-transmit"
    }
   ]
  },
  {
   "title": "receive message rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(vertx_http_server_receive_messages_total[1m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "process time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(vertx_http_server_response_time_seconds_bucket[1m])) * 1000",
     "legendFormat": "0.95-{{kubernetes_pod_name}}"
    },
    {
     "expr": "histogram_quantile(0.5, rate(vertx_http_server_response_time_seconds_bucket[1m])) * 1000",
     "legendFormat": "0.5-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "response code info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(vertx_http_server_requests_total{code=~\"4..\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "4xx-{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(vertx_http_server_requests_total{code=~\"5..\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "5xx-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "success send message rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(vertx_kafka_successfully_send_messages_total[1m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "kafka send time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vertx_http_server_request_send_time_seconds{quantile=\"0.5\"} * 1000",
     "legendFormat": "0.5-{{kubernetes_pod_name}}"
    },
    {
     "expr": "vertx_http_server_request_send_time_seconds{quantile=\"0.95\"} * 1000",
     "legendFormat": "0.95-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "qps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(vertx_http_server_requests_total[1m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}