version: '3'
services:
  mysql:
    restart: always
    image: mysql:5.7.18
    environment:
      - "MYSQL_ROOT_PASSWORD=yourpassword"
      - "MYSQL_DATABASE=yourdbname"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306